server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima59
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.150.128
  rabbitmq:
    host: 192.168.150.128
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.user.pojo
logging:
  level:
    com.leyou: debug